### ISSUE TITLE
rtt.sub has 1 heaptype immediate

### ISSUE THREAD

**Issue by kripken** [WebAssembly/wasp#52]
In the [GC prototype 2](https://docs.google.com/document/d/1DklC3qVuOdLHSXB5UXghM_syCh-4cMinQ50ICiXnK3Q/edit?pli=1#), rtt.sub has 2 heaptype immediates, while wasp seems to emit 1.

Noticed while comparing the behavior of v8, wasp, and binaryen.

cc @jakobkummerow

**Comment by jakobkummerow** [comment]
See comments on that doc: 

> Currently implemented without `<n>` and `<heaptype1>` immediates.

This is (sort of) intentional, as the types specified by the immediates in question can be deduced from the operand stack. Having the immediates makes the modules bigger and validation slower (and, at least in V8, provides zero benefit), so I think it would be nice to drop them from the spec. The implementations in V8 and wasp assume that this is going to happen.

**Comment by kripken** [comment]
Thanks again - was my mistake in missing the notes...
