### ISSUE TITLE
Type casting does not work with complex sample

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/wasp#56]
The follow simple sample:

```
(module
  (type $java/lang/Object (struct
    (field $java/lang/Object..vtable (mut i32))
    (field $java/lang/Object..hashcode (mut i32))
  ))
  (type $java/lang/Class (struct
    (field $java/lang/Class..vtable (mut i32))
    (field $java/lang/Class..hashcode (mut i32))
    (field $java/lang/Class.vtable (mut i32))
  ))
  (func $java/lang/Object.<init>(param $this (ref null $java/lang/Object))
    return
  )
  (func $java/lang/Class.<init>(param $this (ref null $java/lang/Class))(param $vtable i32)
    local.get $this
    call $java/lang/Object.<init>
    local.get $this
    local.get $vtable
    struct.set $java/lang/Class 2 ;; $vtable
    return
  )
)
```
can be converted without any errors with the command line: `wasp wat2wasm --enable-gc --enable-sign-extension test.wat`

With a more complex sample [test.zip](https://github.com/WebAssembly/wasp/files/5824821/test.zip) I received the follow error:

```
test.wat:2817:5: Expected stack to contain [(ref null 86)], got [(ref null 89)]
    call $java/lang/Object.<init>
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

It look like that it can't compare the different types correctly if there are to many types. If there is an error in the sample which I can't see then a better error message would be desirable.

**Comment by binji** [comment]
There was a bug here: the validation was incorrectly caching type conversions, so `IsMatch(x,y)` was always equal to `IsMatch(y,x)`. This means that depending on which checks happen first, the validation may succeed or fail. This is fixed in #58. Perhaps it makes the bug in `test.zip` a little clearer:

```
$ ./wasp wat2wasm --enable-gc --enable-sign-extension test.wat
test.wat:2507:5: Expected stack to contain [(ref null 89)], got [(ref null 86)]
    return
    ^^^^^^
test.wat:2657:7: Expected stack to contain [(ref null 92)], got [(ref null 86)]
      local.set 2
      ^^^^^^^^^^^
```

In the first error, `$java/lang/Object` is being used where `$java/lang/Class` is expected. In the second case, `$java/lang/Object` is being used where `$java/lang/String` is expected. You're right that this would be clearer with a better error message, however.
